### ISSUE TITLE
Add GitHub actions

### ISSUE THREAD

**Issue by ArtyomPanfutov** [ArtyomPanfutov/loan-amortization-calculator#12]

**Comment by Bhavikaso** [comment]
Hi @ArtyomPanfutov ,
Could you please provide me more details here or some reference ? I am thinking to pick this one, but not sure, like what all git actions should be included.

Thank you 
Bhavika

**Comment by ArtyomPanfutov** [comment]
Hi @Bhavikaso! 

I think it would be nice to have an action that builds and runs tests on pull requests or pushes.

Here is a description for Java project: https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven
