### ISSUE TITLE
Improve the Loan Builder API

### ISSUE THREAD

**Issue by ArtyomPanfutov** [ArtyomPanfutov/loan-amortization-calculator#9]
Extend the API of the Loan builder to accept double value (with an encapsulated converting them to BigDecimal).

**Comment by Bhavikaso** [comment]
Hi @ArtyomPanfutov , 
I want to contribute in this and henceforth I made changes and tried pushing this, but getting following failure. 

remote: Permission to ArtyomPanfutov/loan-amortization-calculator.git denied to Bhavikaso.
fatal: unable to access 'https://github.com/ArtyomPanfutov/loan-amortization-calculator.git/': The requested URL returned error: 403

Please, could you guide me how can I contribute here
Thanks
Bhavika

**Comment by ArtyomPanfutov** [comment]
Hi @Bhavikaso!

Could you please describe the steps in more detail? What branch did you try to push? 
I will check the repository settings for new contributors. It might be something wrong there since it is a new project.

As for the contributing guidelines - unfortunately,  they are still under development. But I can describe the steps here:

* Create a branch for this feature.
* Make the changes. Write tests if you think it is necessary.
* Run tests. If some tests fail - find the reason and fix it.
* Create a pull request to the master branch. 

Thank you

**Comment by Bhavikaso** [comment]
Hi @ArtyomPanfutov 
Thank you for sharing the steps. I'm able to create the Pull Request.

Thanks 
Bhavika
